stream: start thread in init_io instead of initialize
We don't want the thread to start before @write has been initialized.
This doesn't change anything about how the streams work because init_io
is called just after the constructor.

This fixes the following error:

    /builds/TankerHQ/sdk-ruby/lib/tanker/core/stream.rb:225: warning: instance variable @write not initialized
    /builds/TankerHQ/sdk-ruby/lib/tanker/core/stream.rb:230: warning: instance variable @write not initialized
    #<Thread:0x0000555778214128 /builds/TankerHQ/sdk-ruby/lib/tanker/core/stream.rb:188 run> terminated with exception (report_on_exception is true):
    /builds/TankerHQ/sdk-ruby/lib/tanker/core/stream.rb:230:in `read_thread': undefined method `close' for nil:NilClass (NoMethodError)
            from /builds/TankerHQ/sdk-ruby/lib/tanker/core/stream.rb:188:in `block in initialize'